services:
  - type: web
    name: business-optima-pdf-analysis
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: OMP_NUM_THREADS
        value: 1
      - key: OPENBLAS_NUM_THREADS
        value: 1
      - key: MKL_NUM_THREADS
        value: 1
      - key: NUMEXPR_NUM_THREADS
        value: 1
    plan: free
    healthCheckPath: /health
